version: '3'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=private

  redis:
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"